sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sdubey695/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sdubey695/react-test npm test

after_success:
  - docker build -t sdubey695/multi-client ./client
  - docker build -t sdubey695/multi-nginx ./nginx
  - docker build -t sdubey695/multi-server ./server
  - docker build -t sdubey695/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_HUB_PSSWD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  #  Take  those images and push them to docker hub
  - docker push sdubey695/multi-client
  - docker push sdubey695/multi-nginx
  - docker push sdubey695/multi-server
  - docker push sdubey695/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-009198312421'
  bucket_path: 'multi-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY