sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sdubey/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sdubey/react-test npm test

after_success:
  - docker build -t sdubey/multi-client ./client
  - docker build -t sdubey/multi-nginx ./nginx
  - docker build -t sdubey/multi-server ./server
  - docker build -t sdubey/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_HUB_PSSWD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sdubey/multi-client
  - docker push sdubey/multi-nginx
  - docker push sdubey/multi-server
  - docker push sdubey/multi-worker
